theme: minima

minima: 
  skin: solarized
  
plugins:
  - jekyll-feed
author:
  name : "Maria do Sameiro Mesquita Gabriel"
title: "Advogada Maria do Sameiro Mesquita Gabriel"
description: "Site da Advogada Maria do Sameiro Mesquita Gabriel"
